# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    pool:
     vmImage: ubuntu-latest
    jobs:
      - job: 
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'ContainerConn'
            repository: 'MyImage'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'

        - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)        
        - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory) 

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        

        - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'